stage_file_proxy.settings:
  type: config_object
  label: 'Stage file proxy settings'
  mapping:
    hotlink:
      type: boolean
      label: "Hotlink"
    origin:
      type: string
      label: "Origin"
      constraints:
        Regex:
          pattern: '/[^\/]$/'
          message: 'Origin cannot end in /'
    origin_dir:
      type: string
      label: "Origin dir"
    proxy_headers:
      type: string
      label: "Proxy headers"
    use_imagecache_root:
      type: boolean
      label: "Use imagecache root"
    verify:
      type: boolean
      label: "Verify SSL"
    excluded_extensions:
      type: string
      label: "Excluded extensions"
